/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ForwarderFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMELOCK_DELAY"
      | "acceptOwnership"
      | "applyMotherWalletChange"
      | "cancelMotherWalletChange"
      | "cancelOwnershipTransfer"
      | "deployAndSweepNative"
      | "deployAndSweepToken"
      | "deployWallet"
      | "emergencyWithdrawNative"
      | "emergencyWithdrawToken"
      | "getAddress"
      | "implementation"
      | "motherWallet"
      | "motherWalletUnlockTime"
      | "owner"
      | "pendingMotherWallet"
      | "pendingOwner"
      | "relayer"
      | "requestMotherWalletChange"
      | "transferOwnership"
      | "updateRelayer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "MotherWalletChangeCancelled"
      | "MotherWalletChangeRequested"
      | "MotherWalletUpdated"
      | "OwnershipTransferCancelled"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "RelayerUpdated"
      | "WalletDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyMotherWalletChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMotherWalletChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOwnershipTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployAndSweepNative",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployAndSweepToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWallet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawNative",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "motherWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "motherWalletUnlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingMotherWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestMotherWalletChange",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRelayer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyMotherWalletChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMotherWalletChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOwnershipTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAndSweepNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAndSweepToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "motherWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "motherWalletUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMotherWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestMotherWalletChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRelayer",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    userId: BigNumberish,
    token: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [userId: bigint, token: string, to: string];
  export interface OutputObject {
    userId: bigint;
    token: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MotherWalletChangeCancelledEvent {
  export type InputTuple = [cancelledAddress: AddressLike];
  export type OutputTuple = [cancelledAddress: string];
  export interface OutputObject {
    cancelledAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MotherWalletChangeRequestedEvent {
  export type InputTuple = [
    newMotherWallet: AddressLike,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [newMotherWallet: string, unlockTime: bigint];
  export interface OutputObject {
    newMotherWallet: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MotherWalletUpdatedEvent {
  export type InputTuple = [
    oldMotherWallet: AddressLike,
    newMotherWallet: AddressLike
  ];
  export type OutputTuple = [oldMotherWallet: string, newMotherWallet: string];
  export interface OutputObject {
    oldMotherWallet: string;
    newMotherWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferCancelledEvent {
  export type InputTuple = [cancelledPendingOwner: AddressLike];
  export type OutputTuple = [cancelledPendingOwner: string];
  export interface OutputObject {
    cancelledPendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [
    currentOwner: AddressLike,
    pendingOwner: AddressLike
  ];
  export type OutputTuple = [currentOwner: string, pendingOwner: string];
  export interface OutputObject {
    currentOwner: string;
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [oldRelayer: AddressLike, newRelayer: AddressLike];
  export type OutputTuple = [oldRelayer: string, newRelayer: string];
  export interface OutputObject {
    oldRelayer: string;
    newRelayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletDeployedEvent {
  export type InputTuple = [userId: BigNumberish, wallet: AddressLike];
  export type OutputTuple = [userId: bigint, wallet: string];
  export interface OutputObject {
    userId: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ForwarderFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ForwarderFactory;
  waitForDeployment(): Promise<this>;

  interface: ForwarderFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  applyMotherWalletChange: TypedContractMethod<[], [void], "nonpayable">;

  cancelMotherWalletChange: TypedContractMethod<[], [void], "nonpayable">;

  cancelOwnershipTransfer: TypedContractMethod<[], [void], "nonpayable">;

  deployAndSweepNative: TypedContractMethod<
    [userId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deployAndSweepToken: TypedContractMethod<
    [userId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  deployWallet: TypedContractMethod<
    [userId: BigNumberish],
    [string],
    "nonpayable"
  >;

  emergencyWithdrawNative: TypedContractMethod<
    [userId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawToken: TypedContractMethod<
    [userId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getAddress: TypedContractMethod<[userId: BigNumberish], [string], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  motherWallet: TypedContractMethod<[], [string], "view">;

  motherWalletUnlockTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingMotherWallet: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  requestMotherWalletChange: TypedContractMethod<
    [newMotherWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRelayer: TypedContractMethod<
    [newRelayer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "applyMotherWalletChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelMotherWalletChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOwnershipTransfer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployAndSweepNative"
  ): TypedContractMethod<[userId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployAndSweepToken"
  ): TypedContractMethod<
    [userId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployWallet"
  ): TypedContractMethod<[userId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawNative"
  ): TypedContractMethod<[userId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawToken"
  ): TypedContractMethod<
    [userId: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[userId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "motherWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "motherWalletUnlockTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingMotherWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestMotherWalletChange"
  ): TypedContractMethod<[newMotherWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRelayer"
  ): TypedContractMethod<[newRelayer: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "MotherWalletChangeCancelled"
  ): TypedContractEvent<
    MotherWalletChangeCancelledEvent.InputTuple,
    MotherWalletChangeCancelledEvent.OutputTuple,
    MotherWalletChangeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MotherWalletChangeRequested"
  ): TypedContractEvent<
    MotherWalletChangeRequestedEvent.InputTuple,
    MotherWalletChangeRequestedEvent.OutputTuple,
    MotherWalletChangeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MotherWalletUpdated"
  ): TypedContractEvent<
    MotherWalletUpdatedEvent.InputTuple,
    MotherWalletUpdatedEvent.OutputTuple,
    MotherWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferCancelled"
  ): TypedContractEvent<
    OwnershipTransferCancelledEvent.InputTuple,
    OwnershipTransferCancelledEvent.OutputTuple,
    OwnershipTransferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WalletDeployed"
  ): TypedContractEvent<
    WalletDeployedEvent.InputTuple,
    WalletDeployedEvent.OutputTuple,
    WalletDeployedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(uint256,address,address)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "MotherWalletChangeCancelled(address)": TypedContractEvent<
      MotherWalletChangeCancelledEvent.InputTuple,
      MotherWalletChangeCancelledEvent.OutputTuple,
      MotherWalletChangeCancelledEvent.OutputObject
    >;
    MotherWalletChangeCancelled: TypedContractEvent<
      MotherWalletChangeCancelledEvent.InputTuple,
      MotherWalletChangeCancelledEvent.OutputTuple,
      MotherWalletChangeCancelledEvent.OutputObject
    >;

    "MotherWalletChangeRequested(address,uint256)": TypedContractEvent<
      MotherWalletChangeRequestedEvent.InputTuple,
      MotherWalletChangeRequestedEvent.OutputTuple,
      MotherWalletChangeRequestedEvent.OutputObject
    >;
    MotherWalletChangeRequested: TypedContractEvent<
      MotherWalletChangeRequestedEvent.InputTuple,
      MotherWalletChangeRequestedEvent.OutputTuple,
      MotherWalletChangeRequestedEvent.OutputObject
    >;

    "MotherWalletUpdated(address,address)": TypedContractEvent<
      MotherWalletUpdatedEvent.InputTuple,
      MotherWalletUpdatedEvent.OutputTuple,
      MotherWalletUpdatedEvent.OutputObject
    >;
    MotherWalletUpdated: TypedContractEvent<
      MotherWalletUpdatedEvent.InputTuple,
      MotherWalletUpdatedEvent.OutputTuple,
      MotherWalletUpdatedEvent.OutputObject
    >;

    "OwnershipTransferCancelled(address)": TypedContractEvent<
      OwnershipTransferCancelledEvent.InputTuple,
      OwnershipTransferCancelledEvent.OutputTuple,
      OwnershipTransferCancelledEvent.OutputObject
    >;
    OwnershipTransferCancelled: TypedContractEvent<
      OwnershipTransferCancelledEvent.InputTuple,
      OwnershipTransferCancelledEvent.OutputTuple,
      OwnershipTransferCancelledEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RelayerUpdated(address,address)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;

    "WalletDeployed(uint256,address)": TypedContractEvent<
      WalletDeployedEvent.InputTuple,
      WalletDeployedEvent.OutputTuple,
      WalletDeployedEvent.OutputObject
    >;
    WalletDeployed: TypedContractEvent<
      WalletDeployedEvent.InputTuple,
      WalletDeployedEvent.OutputTuple,
      WalletDeployedEvent.OutputObject
    >;
  };
}
