/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as forwarderSol from "./Forwarder.sol";
export type { forwarderSol };
export type { ForwarderFactory } from "./ForwarderFactory";
export type { MockBEP20 } from "./MockBEP20";
