root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  cmd = "go build -o ./tmp/server ./cmd/server"
  delay = 500
  exclude_dir = ["tmp", "lib", "out", "cache", "broadcast", "artifacts", "node_modules", "bin"]
  include_ext = ["go", "json"]
  send_interrupt = true
  kill_delay = "500ms"

[log]
  time = true

[misc]
  clean_on_exit = true
