/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFactory,
  IFactoryInterface,
} from "../../../contracts/Forwarder.sol/IFactory";

const _abi = [
  {
    inputs: [],
    name: "motherWallet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryInterface {
    return new Interface(_abi) as IFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFactory {
    return new Contract(address, _abi, runner) as unknown as IFactory;
  }
}
