/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ForwarderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emergencyWithdrawNative"
      | "emergencyWithdrawToken"
      | "factory"
      | "sweepNative"
      | "sweepToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdrawNative"
      | "EmergencyWithdrawToken"
      | "Received"
      | "SweptNative"
      | "SweptToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emergencyWithdrawNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sweepNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sweepToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "emergencyWithdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sweepNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweepToken", data: BytesLike): Result;
}

export namespace EmergencyWithdrawNativeEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawTokenEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweptNativeEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweptTokenEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Forwarder extends BaseContract {
  connect(runner?: ContractRunner | null): Forwarder;
  waitForDeployment(): Promise<this>;

  interface: ForwarderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emergencyWithdrawNative: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdrawToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  sweepNative: TypedContractMethod<[], [void], "nonpayable">;

  sweepToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emergencyWithdrawNative"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sweepNative"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sweepToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EmergencyWithdrawNative"
  ): TypedContractEvent<
    EmergencyWithdrawNativeEvent.InputTuple,
    EmergencyWithdrawNativeEvent.OutputTuple,
    EmergencyWithdrawNativeEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawToken"
  ): TypedContractEvent<
    EmergencyWithdrawTokenEvent.InputTuple,
    EmergencyWithdrawTokenEvent.OutputTuple,
    EmergencyWithdrawTokenEvent.OutputObject
  >;
  getEvent(
    key: "Received"
  ): TypedContractEvent<
    ReceivedEvent.InputTuple,
    ReceivedEvent.OutputTuple,
    ReceivedEvent.OutputObject
  >;
  getEvent(
    key: "SweptNative"
  ): TypedContractEvent<
    SweptNativeEvent.InputTuple,
    SweptNativeEvent.OutputTuple,
    SweptNativeEvent.OutputObject
  >;
  getEvent(
    key: "SweptToken"
  ): TypedContractEvent<
    SweptTokenEvent.InputTuple,
    SweptTokenEvent.OutputTuple,
    SweptTokenEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdrawNative(address,uint256)": TypedContractEvent<
      EmergencyWithdrawNativeEvent.InputTuple,
      EmergencyWithdrawNativeEvent.OutputTuple,
      EmergencyWithdrawNativeEvent.OutputObject
    >;
    EmergencyWithdrawNative: TypedContractEvent<
      EmergencyWithdrawNativeEvent.InputTuple,
      EmergencyWithdrawNativeEvent.OutputTuple,
      EmergencyWithdrawNativeEvent.OutputObject
    >;

    "EmergencyWithdrawToken(address,address,uint256)": TypedContractEvent<
      EmergencyWithdrawTokenEvent.InputTuple,
      EmergencyWithdrawTokenEvent.OutputTuple,
      EmergencyWithdrawTokenEvent.OutputObject
    >;
    EmergencyWithdrawToken: TypedContractEvent<
      EmergencyWithdrawTokenEvent.InputTuple,
      EmergencyWithdrawTokenEvent.OutputTuple,
      EmergencyWithdrawTokenEvent.OutputObject
    >;

    "Received(address,uint256)": TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;
    Received: TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;

    "SweptNative(address,uint256)": TypedContractEvent<
      SweptNativeEvent.InputTuple,
      SweptNativeEvent.OutputTuple,
      SweptNativeEvent.OutputObject
    >;
    SweptNative: TypedContractEvent<
      SweptNativeEvent.InputTuple,
      SweptNativeEvent.OutputTuple,
      SweptNativeEvent.OutputObject
    >;

    "SweptToken(address,address,uint256)": TypedContractEvent<
      SweptTokenEvent.InputTuple,
      SweptTokenEvent.OutputTuple,
      SweptTokenEvent.OutputObject
    >;
    SweptToken: TypedContractEvent<
      SweptTokenEvent.InputTuple,
      SweptTokenEvent.OutputTuple,
      SweptTokenEvent.OutputObject
    >;
  };
}
